plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.hilt) apply false
    alias(libs.plugins.google.services) apply false
    alias(libs.plugins.sonarqube)
    alias(libs.plugins.kover) apply false
}

// ──────────────────────────────────────────────────────────────────────────
//  SonarQube
// ──────────────────────────────────────────────────────────────────────────
//  Run a full analysis with:  ./gradlew testDebugUnitTest koverXmlReportDebug sonar
//  (or use scripts/sonar-scan.ps1 / scripts/sonar-scan.sh which wrap that).
//
//  The sonarqube Gradle plugin auto-detects the AGP source/test/bytecode
//  layout, so we only declare project identity, the Kover coverage XML, and
//  the analysis/coverage exclusions. Nothing here touches a database or any
//  runtime state — Sonar is a pure static-analysis pass over source files.
// ──────────────────────────────────────────────────────────────────────────
sonar {
    properties {
        property("sonar.projectKey", "Bug-Hunter-Android")
        property("sonar.projectName", "Bug Hunter Android")
        property("sonar.projectVersion", "2.9")
        property("sonar.host.url", System.getenv("SONAR_HOST_URL") ?: "http://localhost:9000")
        property("sonar.sourceEncoding", "UTF-8")

        // Kover emits a JaCoCo-format XML that SonarPython/SonarKotlin reads
        // through this property. Generated by `koverXmlReportDebug`.
        property(
            "sonar.coverage.jacoco.xmlReportPaths",
            "${rootDir}/app/build/reports/kover/reportDebug.xml",
        )

        // `sonar.coverage.exclusions` removes files from the Coverage%
        // denominator WITHOUT hiding them from quality analysis. Compose UI,
        // theme, navigation graphs, DI wiring, the Application/Activity
        // entry points and generated code are exercised by instrumented
        // (emulator) tests, not JVM unit tests — counting them here would
        // wrongly crater the coverage number the gate reads. They are still
        // fully SCANNED for code smells / bugs.
        property(
            "sonar.coverage.exclusions",
            listOf(
                "**/ui/theme/**",
                "**/ui/components/**",
                "**/core/nav/**",
                "**/di/**",
                "**/feature/analytics/charts/**",
                "**/feature/chatbot/blocks/**",
                "**/feature/chatbot/messages/**",
                "**/feature/chatbot/tabs/**",
                "**/*Screen.kt",
                "**/*Composable*.kt",
                "**/*Preview*.kt",
                // Compose UI by naming convention (dialogs, panels, overlays,
                // FABs, sections, sheets, rows, cards, pickers, block
                // renderers, prompts, banners, composers, footers). Verified
                // every matching file is @Composable — exercised by
                // instrumented tests, not JVM unit tests.
                "**/*Dialog.kt",
                "**/*Panel.kt",
                "**/*Overlay.kt",
                "**/*Fab.kt",
                "**/*Section.kt",
                "**/*BottomSheet.kt",
                "**/*Row.kt",
                "**/*Card.kt",
                "**/*Picker.kt",
                "**/*Renderer.kt",
                "**/*Prompt.kt",
                "**/*Banner.kt",
                "**/*Composer.kt",
                "**/*Footer.kt",
                // Android-framework-coupled infra: push (FCM service, the
                // registration worker, token syncer, channel registration),
                // the Hilt network module, and the EncryptedSharedPreferences
                // wrapper — none unit-testable on the JVM.
                "**/core/push/**",
                "**/NetworkModule.kt",
                "**/MoshiModule.kt",
                "**/data/local/EncryptedPrefs.kt",
                "**/MainActivity.kt",
                "**/*Application.kt",
                "**/BuildConfig.*",
            ).joinToString(","),
        )

        // Things to never scan at all: generated build artifacts, the
        // Gradle/IDE cruft, and `font_certs.xml` — a vendored Google Fonts
        // certificate table whose base64 SHA hashes the Typos analyzer
        // (wrongly) flags as 21 misspellings.
        //
        // `src/debug/**` is the debug-only manifest overlay + network config;
        // it is never part of a release APK. Sonar's XML analyzer reads each
        // manifest in isolation (it cannot see Android manifest merging), so
        // it flags the overlay's bare <application> element for the backup
        // hotspot even though the merged manifest carries the real backup
        // config (backup_rules.xml / data_extraction_rules.xml exclude the
        // session cookies and auth DataStore). Excluding the dev-only overlay
        // keeps the analysis focused on what actually ships.
        property(
            "sonar.exclusions",
            listOf(
                "**/build/**",
                "**/*.kts",
                "**/google-services.json",
                "**/res/values/font_certs.xml",
                "**/src/debug/**",
            ).joinToString(","),
        )

        // -------------------------------------------------------------------
        //  Justified rule suppressions (mirrors the backend repos' approach).
        // -------------------------------------------------------------------
        property(
            "sonar.issue.ignore.multicriteria",
            "s107ui,s107api,sdkint,dispatch,hiltmod," +
                "s3776a,s3776b,s3776c,s3776d,s3776e,s3776f,s3776g," +
                "s1172a,s1172b,s1172c,s1172d",
        )
        // S107 (too many parameters): @Composable functions hoist state
        // through their parameter list — 7+ params is the Compose idiom, not
        // a smell. Same for Retrofit interfaces, where each query filter is a
        // parameter (cf. the backend's list_bugs S107 suppression).
        property("sonar.issue.ignore.multicriteria.s107ui.ruleKey", "kotlin:S107")
        property("sonar.issue.ignore.multicriteria.s107ui.resourceKey", "**/feature/**/*.kt")
        property("sonar.issue.ignore.multicriteria.s107api.ruleKey", "kotlin:S107")
        property("sonar.issue.ignore.multicriteria.s107api.resourceKey", "**/core/**/*.kt")
        // ObsoleteSdkInt: the SDK_INT guards are deliberately kept for
        // explicitness / a future minSdk drop (documented in-source, e.g.
        // NotificationChannels.registerAll).
        property("sonar.issue.ignore.multicriteria.sdkint.ruleKey", "external_android-lint:ObsoleteSdkInt")
        property("sonar.issue.ignore.multicriteria.sdkint.resourceKey", "**/*.kt")
        // S6310 (hardcoded Dispatchers.IO): the file-export / upload use-cases
        // legitimately pin IO; they're covered through their ViewModels.
        property("sonar.issue.ignore.multicriteria.dispatch.ruleKey", "kotlin:S6310")
        property("sonar.issue.ignore.multicriteria.dispatch.resourceKey", "**/*.kt")
        // S6517: Hilt @Module/@Binds interfaces MUST be regular interfaces —
        // they can't be `fun interface`s, so this is a framework false positive.
        property("sonar.issue.ignore.multicriteria.hiltmod.ruleKey", "kotlin:S6517")
        property("sonar.issue.ignore.multicriteria.hiltmod.resourceKey", "**/PushTokenSyncer.kt")
        // S3776 (cognitive complexity) on @Composable functions: the
        // complexity is structural (conditional UI layout), not branching
        // logic, and Compose has no clean sub-function extraction for it.
        // Suppressed only on the specific Composable/theme files that trip
        // it — never on *ViewModel.kt, where complexity IS a real signal.
        // The one piece of genuine parsing logic (BhRichHtml) is refactored
        // in code instead of suppressed.
        property("sonar.issue.ignore.multicriteria.s3776a.ruleKey", "kotlin:S3776")
        property("sonar.issue.ignore.multicriteria.s3776a.resourceKey", "**/*Screen.kt")
        property("sonar.issue.ignore.multicriteria.s3776b.ruleKey", "kotlin:S3776")
        property("sonar.issue.ignore.multicriteria.s3776b.resourceKey", "**/BhAppShell.kt")
        property("sonar.issue.ignore.multicriteria.s3776c.ruleKey", "kotlin:S3776")
        property("sonar.issue.ignore.multicriteria.s3776c.resourceKey", "**/BhTextField.kt")
        property("sonar.issue.ignore.multicriteria.s3776d.ruleKey", "kotlin:S3776")
        property("sonar.issue.ignore.multicriteria.s3776d.resourceKey", "**/BrandTokens.kt")
        property("sonar.issue.ignore.multicriteria.s3776e.ruleKey", "kotlin:S3776")
        property("sonar.issue.ignore.multicriteria.s3776e.resourceKey", "**/SleuthPanel.kt")
        property("sonar.issue.ignore.multicriteria.s3776f.ruleKey", "kotlin:S3776")
        property("sonar.issue.ignore.multicriteria.s3776f.resourceKey", "**/TypeTabsComposable.kt")
        // BhRichHtml is a Compose AnnotatedString builder (HTML token stream ->
        // styled spans). Its branching is the inherent shape of an inline-
        // markup renderer; splitting it would just scatter the span state.
        property("sonar.issue.ignore.multicriteria.s3776g.ruleKey", "kotlin:S3776")
        property("sonar.issue.ignore.multicriteria.s3776g.resourceKey", "**/BhRichHtml.kt")
        // S1172 (unused param) on Composables: a handful of screens/rows keep
        // a hoisted callback or nav-arg param that the current layout doesn't
        // read, but callers still supply — removing it would churn call sites
        // for no behaviour change. (The one non-UI case, AuthInterceptor, is
        // fixed in code.)
        property("sonar.issue.ignore.multicriteria.s1172a.ruleKey", "kotlin:S1172")
        property("sonar.issue.ignore.multicriteria.s1172a.resourceKey", "**/*Screen.kt")
        property("sonar.issue.ignore.multicriteria.s1172b.ruleKey", "kotlin:S1172")
        property("sonar.issue.ignore.multicriteria.s1172b.resourceKey", "**/BugRow.kt")
        property("sonar.issue.ignore.multicriteria.s1172c.ruleKey", "kotlin:S1172")
        property("sonar.issue.ignore.multicriteria.s1172c.resourceKey", "**/FilterBarComposable.kt")
        property("sonar.issue.ignore.multicriteria.s1172d.ruleKey", "kotlin:S1172")
        property("sonar.issue.ignore.multicriteria.s1172d.resourceKey", "**/SavedViewsBottomSheet.kt")
    }
}
